pipeline {
    agent any

    tools {
        maven 'Maven_3'
        jdk 'JDK21'
        dockerTool 'Docker'
    }

    environment {
        REGISTRY_URL = "localhost:5000"
        DOCKER_HOME  = tool 'Docker'
        PATH         = "${DOCKER_HOME}/bin:${env.PATH}"
        IMAGE_NAME   = "employee-service"
        IMAGE_TAG    = "latest"
        NAMESPACE    = "microservices"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/anuragsingh200683-ui/enterprise-microservices-observability-platform.git'
            }
        }

        stage('Build JAR') {
            steps {
                dir('employee-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('employee-service') {
                    sh """
                        docker build -t ${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG} .
                        docker push ${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh """
                    kubectl apply -f platform/namespace.yaml
                    kubectl apply -f platform/microservices-configmap.yaml
                    kubectl apply -f employee-service/k8deployment/deployment.yaml
                    kubectl rollout restart deployment/${IMAGE_NAME} -n ${NAMESPACE}
                """
            }
        }

        stage('Verify Deployment') {
            steps {
                sh """
                    kubectl rollout status deployment/${IMAGE_NAME} -n ${NAMESPACE} --timeout=180s
                    kubectl get pods -n ${NAMESPACE} -o wide
                    kubectl get svc -n ${NAMESPACE}
                    kubectl exec -n ${NAMESPACE} deploy/${IMAGE_NAME} -- wget -qO- http://localhost:8081/actuator/health/readiness
                """
            }
        }
    }

    post {
        success {
            echo "employee-service build #${env.BUILD_NUMBER} deployed successfully."
        }
        failure {
            echo "employee-service build #${env.BUILD_NUMBER} failed - check stage logs above."
        }
    }
}
